# Servis diffamr robotunun servislerini kontrol etmek için oluşturulmuştur.
# 
# Bu servis iki farklı request almaktadır. Bunlar:
# 
#   pin     Pin numarası
#   state   Ayarlanacak değer (ON-OFF)

# Geçerli fonksiyon değerleri

# pin requesti için geçerli PIN değerleri
int8 PIN_0 = 0
int8 PIN_1 = 1
int8 PIN_2 = 2
int8 PIN_3 = 3
int8 PIN_4 = 4
int8 PIN_5 = 5
int8 PIN_6 = 6
int8 PIN_7 = 7
int8 PIN_8 = 8 #Lift Down
int8 PIN_9 = 9 #Lift Up


# state requesti için geçerli IO değerleri
int8 STATE_OFF  = 0
int8 STATE_ON   = 1


#Request alanları
int8 pin
int8 state
---
bool success